name: build

on: [push]

jobs:

  build:
    name: Build GitHubActionsDataCollector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Output dotnet info
        run: dotnet --info

      - name: Restore GitHubActionsDataCollector.sln
        run: |
          dotnet restore ./GitHubActionsDataCollector.sln --verbosity m

      - name: Build GitHubActionsDataCollector.sln
        run: |
          dotnet build ./GitHubActionsDataCollector.sln --configuration Release --no-restore


  test:
    name: Test GitHubActionsDataCollector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Output dotnet info
        run: dotnet --info

      - name: Restore GitHubActionsDataCollector.sln
        run: |
          dotnet restore ./GitHubActionsDataCollector.sln --verbosity m

      - name: Build GitHubActionsDataCollector.sln
        run: |
          dotnet build ./GitHubActionsDataCollector.sln --configuration Release --no-restore

      - name: Test GitHubActionsDataCollector.sln
        run: |
          dotnet test ./GitHubActionsDataCollector.UnitTests/GitHubActionsDataCollector.UnitTests.csproj --no-build --filter "Category!=Manual" --no-restore --verbosity detailed
