name: build

on: [push]

jobs:

  build:
    name: Build GitHubActionsDataCollector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Output dotnet info
        run: dotnet --info

      - name: Restore GitHubActionsDataCollector.sln
        run: |
          dotnet restore ./GitHubActionsDataCollector.sln --verbosity m

      - name: Build GitHubActionsDataCollector.sln
        run: |
          dotnet build ./GitHubActionsDataCollector.sln --configuration Release --no-restore


  test:
    name: Test GitHubActionsDataCollector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Output dotnet info
        run: dotnet --info

      - name: Restore GitHubActionsDataCollector.UnitTests
        run: |
          dotnet restore ./GitHubActionsDataCollector.UnitTests/GitHubActionsDataCollector.UnitTests.csproj --verbosity m

      - name: Build GitHubActionsDataCollector.UnitTests
        run: |
          dotnet build ./GitHubActionsDataCollector.UnitTests/GitHubActionsDataCollector.UnitTests.csproj --configuration Release --no-restore

      - name: Get failed tests
        uses: jameschristou/actions-get-failed-tests-from-artifacts@aaf8bc7de9163bd70f99e5c1d6e84b41c33ca336
        id: get_failed_tests
        with:
            name_of_the_test_run: "Test GitHubActionsDataCollector"

      - name: Update test filter
        id: update_test_filter
        run: |
            tests_filter=""

            for failed_test in $(${{steps.get_failed_tests.outputs.failed_tests}} | jq -c '.[]); do
                echo "Test found: ${failed_test}"
                tests_filter+="FullyQualifiedName=${failed_test}|"
            done

            tests_filter="${tests_filter%?}"  # Remove the trailing |

            echo "tests_filter:${tests_filter}"
            echo "tests_filter=$tests_filter" >> $GITHUB_OUTPUT
        shell: bash

      - name: Test GitHubActionsDataCollector.UnitTests
        run: |
          dotnet test ./GitHubActionsDataCollector.UnitTests/GitHubActionsDataCollector.UnitTests.csproj --configuration Release --no-restore --no-build --filter "${{steps.update_test_filter.outputs.tests_filter}}" --verbosity normal '-l:trx;LogFileName=testresults-attempt-${{github.run_attempt}}.xml'

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: Test Results for Attempt-${{github.run_attempt}}
            path: ./GitHubActionsDataCollector.UnitTests/TestResults/testresults-attempt-${{github.run_attempt}}.xml

      - name: Get failed tests
        uses: jameschristou/actions-get-failed-tests-from-artifacts@aaf8bc7de9163bd70f99e5c1d6e84b41c33ca336
        with:
            name_of_the_test_run: "Test GitHubActionsDataCollector"
