name: build

on: [push]

jobs:

  build:
    name: Build GitHubActionsDataCollector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Output dotnet info
        run: dotnet --info

      - name: Restore GitHubActionsDataCollector.sln
        run: |
          dotnet restore ./GitHubActionsDataCollector.sln --verbosity m

      - name: Build GitHubActionsDataCollector.sln
        run: |
          dotnet build ./GitHubActionsDataCollector.sln --configuration Release --no-restore


  test:
    name: Test GitHubActionsDataCollector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Output dotnet info
        run: dotnet --info

      - name: Restore GitHubActionsDataCollector.UnitTests
        run: |
          dotnet restore ./GitHubActionsDataCollector.UnitTests/GitHubActionsDataCollector.UnitTests.csproj --verbosity m

      - name: Build GitHubActionsDataCollector.UnitTests
        run: |
          dotnet build ./GitHubActionsDataCollector.UnitTests/GitHubActionsDataCollector.UnitTests.csproj --configuration Release --no-restore

      - name: Test GitHubActionsDataCollector.UnitTests
        run: |
          dotnet test ./GitHubActionsDataCollector.UnitTests/GitHubActionsDataCollector.UnitTests.csproj --filter "Category!=Manual" --verbosity detailed
